#NumPy and Basic Pandas

#Introduction
Now that we have introduced the fundamentals of Python, it's time to learn about NumPy and Pandas.

#NumPy
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [1]:
import numpy as np

#Basic NumPy Arrays
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [2]:
price_list = [200, 300, 400, 500, 600]
price_array = np.array(price_list)
print(price_array, type(price_array))

[200 300 400 500 600] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. If we pass np.array() a list of lists, it will create a 2-dimensional array.



In [5]:
Ar = np.array([[4,2],[2,4],[3,6]])
print(Ar, type(Ar))

[[4 2]
 [2 4]
 [3 6]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:



In [6]:
print(Ar.shape)

(3, 2)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:



In [8]:
print(Ar[0])
print(Ar[1])
print(Ar[2])

[4 2]
[2 4]
[3 6]


If we want to access the matrix by column instead:

In [11]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [4 2 3]
the second column:  [2 4 6]


#Array Functions
Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [12]:
print(np.log(price_array))

[5.29831737 5.70378247 5.99146455 6.2146081  6.39692966]


Other functions return a single value:

In [13]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

400.0
141.4213562373095
2000
600


The functions above return the mean, standard deviation, total and maximum value of an array.

#Pandas
Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [14]:
import pandas as pd

#Series
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [18]:
price = [5, 4, 3, 2, 1, 0]
s = pd.Series(price)
s

0    5
1    4
2    3
3    2
4    1
5    0
dtype: int64

We can customize the indices of a new Series:

In [19]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    5
b    4
c    3
d    2
e    1
f    0
dtype: int64

Or we can change the indices of an existing Series:

In [20]:
s.index = [6,5,4,3,2,1]
s

6    5
5    4
4    3
3    2
2    1
1    0
dtype: int64

Series is like a list since it can be sliced by index:

In [21]:
print(s[1:])
print(s[:-2])

5    4
4    3
3    2
2    1
1    0
dtype: int64
6    5
5    4
4    3
3    2
dtype: int64


Series is also like a dictionary whose values can be set or fetched by index label:

In [22]:
print(s[4])
s[4] = 0
print(s)

3
6    5
5    4
4    0
3    2
2    1
1    0
dtype: int64


Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.

In [23]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    5
1    4
2    3
3    2
4    1
5    0
Name: Apple Price List, dtype: int64
Apple Price List


We can get the statistical summaries of a Series:

In [24]:
print(s.describe())

count    6.000000
mean     2.500000
std      1.870829
min      0.000000
25%      1.250000
50%      2.500000
75%      3.750000
max      5.000000
Name: Apple Price List, dtype: float64


#Time Index
Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:

In [25]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    5
2017-01-02    4
2017-01-03    3
2017-01-04    2
2017-01-05    1
2017-01-06    0
Freq: D, Name: Apple Price List, dtype: int64


Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:



In [26]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    5
5    4
4    3
3    2
2    1
1    0
Name: Apple Price List, dtype: int64
0


If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:



In [27]:
print(s.iloc[1])

4


While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.

In [28]:
s.index = time_index
print(s['2017-01-03'])

3


We can even access to a range of dates:

In [29]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    4
2017-01-03    3
2017-01-04    2
2017-01-05    1
Freq: D, Name: Apple Price List, dtype: int64


Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:

In [30]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-04    2
2017-01-05    1
2017-01-06    0
Freq: D, Name: Apple Price List, dtype: int64
[2017-01-01     True
2017-01-02     True
2017-01-03     True
2017-01-04    False
2017-01-05    False
2017-01-06    False
Freq: D, Name: Apple Price List, dtype: bool]


As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

#Summary
Here we have introduced NumPy and Pandas for scientific computing in Python. In the next chapter, we will dive into Pandas to learn resampling and manipulating Pandas DataFrame, which are commonly used in financial data analysis.